name: issue801

on:
  workflow_dispatch:

jobs:
  testjob:
    name: pip
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: '/home/runner/work/setup-python-testaparna/setup-python-testaparna/pnpm-lock.yaml'

      - name: Verify pnpm-lock.yaml Path
        run: |
          echo "Current directory: $(pwd)"
          ls -al /home/runner/work/setup-python-testaparna/setup-python-testaparna/pnpm-lock.yaml
