name: Release Workflow

on:
  release:
    types: [created, published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Publish
        id: publish
        uses: actions/publish-immutable-action@0.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
