name: test cache error message

on:
 workflow_dispatch:

jobs:
  testjob_pip:
    name: test cache pip
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: aparnajyothi-y/setup-python@update-error-message 
        with:
          python-version: '3.7'
          architecture: x64
          cache: "pip"

      

  testjob_pipenv:
     name: test cache pipenv
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v4
       - uses: aparnajyothi-y/setup-python@update-error-message  
         with:
           python-version: '3.7'
           architecture: x64
           cache: "pipenv"
      

  testjob_poetry:
     name: test cache poetry
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v4
       - uses: aparnajyothi-y/setup-python@update-error-message 
         with:
           python-version: '3.7'
           architecture: x64
           cache: "poetry"

       

      
            
      
