name: Test Python Tk

on: 
   workflow_dispatch : 

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.11

    - name: Reinstall tcl-tk
      run: brew reinstall tcl-tk

    - name: Run script
      run: python tk_min.py
