name: test ubuntu-24.04

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # You can specify your Python version here
        

    - name: Install dependencies
      run: |
        pip install pipenv
