name: Test#938

on:
 workflow_dispatch:
      
jobs:
  test-python:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macOS-13]
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python from pyproject.toml
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      
  test-python-setup-fix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macOS-13]
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python from pyproject.toml
        uses: priya-kinthali/setup-python@fix-935-toml
        with:
          python-version-file: pyproject.toml
      
